### ISSUE TITLE
Package differently?

### ISSUE THREAD

**Issue by Jeppedy** [plaintextpackets/netprobe_lite#13]
I thank you so much for writing this and putting it together.
I wonder if now that you have it rolling along, you might consider publishing out an image.  We could just pull down the image, create our volumes and drop the env file(s) into the external volume.
The way it is now, I build everything by following your directions, but then I make a Docker Compose inside Portainer that references the previously-built images.

Could be so much more convenient if you published the image.  But I know, only so much time in the day!

**Comment by plaintextpackets** [comment]
Thanks for posting yeah I'm considering that, just need the time to compile it all into one image, right now using separate images made it super quick to get it up and running

**Comment by plaintextpackets** [comment]
I now realize the other issue, I didn't want to pay for Docker hosting LOL

**Comment by Jeppedy** [comment]
I didn't realize you had to.  I'll look into it, but I thought the docker.io
hub was free to post to.

**Comment by Jeppedy** [comment]
Looks like until it takes off, you could use the free plan.  If you need
more, then yeah, it's $60/year.  True.

**Comment by plaintextpackets** [comment]
Yeah just read through it. Ok I'll add that to the backlog. I also want to test a smaller image

**Comment by Jeppedy** [comment]
If I can help you in any way, please let me know.

**Comment by PISTOLCUPCAKES** [comment]
I'll second this request and add (although I'm not sure if it's a better/worse option in this instance) there's also the [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

**Comment by plaintextpackets** [comment]
I compiled the image and posted to Dockerhub, if you have cycles to help me test:

https://github.com/plaintextpackets/netprobe_lite/tree/compiled_image

It's a pretty simple change and should avoid any of the issues with Docker building on various platforms

**Comment by plaintextpackets** [comment]
https://github.com/plaintextpackets/netprobe_lite/releases/tag/v1.1.0

**Comment by plaintextpackets** [comment]
Done in v1.1.0

**Comment by PISTOLCUPCAKES** [comment]
Not sure if I'm missing something here or what but I can't get it to run using the dockerhub image. I've cloned the github repo and pulled down the docker image. I've tried passing path <github_repo_path>:/netprobe_lite and it still fails to start with no logs. Can you share your bind variables/paths for using the image? Something else I may be doing wrong here?

**Comment by Jeppedy** [comment]
Testing now...
Away from home, and it seems something isn't quite right.  I'll debug
tomorrow.  Likely on my end...

**Comment by plaintextpackets** [comment]
Hmm are you still starting up via compose? The only image that I uploaded was for the main Netprobe image but still needs redis prom grafana which I did not combine

**Comment by Jeppedy** [comment]
Got it!

Pulled out some of the unneeded entries to slim it down and avoid conflicts
for some (especially the network sections)


# NetProbe using shared repository

services:
  redis:
    restart: unless-stopped
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      -
/home/jherr/docker-containers/netprobe_lite/config/redis/redis.conf:/etc/redis/redis.conf

  netprobe:
    restart: unless-stopped
    container_name: netprobe-probe
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite:/netprobe_lite
    environment:
      MODULE: "NETPROBE"

  presentation:
    restart: unless-stopped
    container_name: netprobe-presentation
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"

  prometheus:
    restart: unless-stopped
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      -
/home/jherr/docker-containers/netprobe_lite/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    restart: unless-stopped
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      -
/home/jherr/docker-containers/netprobe_lite/config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      -
/home/jherr/docker-containers/netprobe_lite/config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      -
/home/jherr/docker-containers/netprobe_lite/config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
    ports:
      - '3001:3000'

**Comment by plaintextpackets** [comment]
Does it work now?

**Comment by Jeppedy** [comment]
# NetProbe using shared repository

services:
  redis:
    restart: unless-stopped
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite/config/redis/redis.conf:/etc/redis/redis.conf

  netprobe:
    restart: unless-stopped
    container_name: netprobe-probe
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite:/netprobe_lite
    environment:
      MODULE: "NETPROBE"

  presentation:
    restart: unless-stopped
    container_name: netprobe-presentation
    image: "plaintextpackets/netprobe:latest"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"

  prometheus:
    restart: unless-stopped
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - /home/jherr/docker-containers/netprobe_lite/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    restart: unless-stopped
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - /home/jherr/docker-containers/netprobe_lite/config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - /home/jherr/docker-containers/netprobe_lite/config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - /home/jherr/docker-containers/netprobe_lite/config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
    ports:
      - '3001:3000'
``

**Comment by Jeppedy** [comment]
> Does it work now?

Works great!  See my compose, above.
I had to name it docker-compose.yaml, BTW, to get it found by the default name sought by Docker Compose

**Comment by Jeppedy** [comment]
Wait...  Runs great, but when I stop and restart the stack, Grafana resets back to the default password and runs the migration jobs again.
Is there a volume that needs to be mapped to local?  Or is it resetting a startup file in that location that you expect to be there from your container, maybe?

**Comment by plaintextpackets** [comment]
So I think I need to explicitly map some more volumes. On both my test machines (Windows and Ubuntu) when Docker runs it automatically persists the data, but maybe that is just a default behavior. 

Going to test some things, any ideas appereciated

**Comment by Jeppedy** [comment]
How are you referencing the Prometheus data store from Grafana?  Are you using the container name or a hard-coded IP?  I'm guessing your doing it right or it likely wouldn't connect at all...

**Comment by plaintextpackets** [comment]
I think I know the issue. I am not explicitly providing a data storage volume for either prometheus or grafana. For some reason on my devices that data somehow gets stored in a temporary volume but then kept, whereas others it gets cleaned up.

I should be doing something like this:

prometheus:
  restart: always
  container_name: netprobe-prometheus
  image: "prom/prometheus"
  volumes:
    - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    **- prometheus_data:/prometheus/data  # Mount a volume for data persistence**
  networks:
    - custom_network  # Attach to the custom network

volumes:
  **prometheus_data:  # Define a volume for Prometheus data persistence**

**Comment by Jeppedy** [comment]
Try adding this volume...
it’s stored in the grafana database which can be sqlite3 database (default, stored in /var/lib/grafana/grafana.db), postgres or mysql (depending on how you configured grafana).

I'm concerned though because I'm not familiar with how to map both a specific file and a parent directory.
Maybe we should let it run to create default files, then stop, copy in dashboards file and restart?

**Comment by Jeppedy** [comment]
Makes sense.  Same issue with Grafana for user accounts.  See previous post.

**Comment by plaintextpackets** [comment]
I'll get something together this evening and post for testing

**Comment by Jeppedy** [comment]
Confirmed...  /var/lib/Grafana needs to persist, or at least one of the files in it does.
And mapping a vol to a file name only works as expected when the file exists before starting the first time, else docker makes a folder the name of the file.

**Comment by plaintextpackets** [comment]
Here's what I'm testing right now:

1. Created two folders in the repo:
/data/grafana
/data/prometheus

2. Set gitignores to ignore the contents which are created at runtime in the repo

3. Set the build config for those two as follows:

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      **- ./data/prometheus:/prometheus**
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - custom_network  # Attach to the custom network

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - ./config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - ./config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
      **- ./data/grafana:/var/lib/grafana**
    ports:
      - '3001:3000'
    networks:
      - custom_network  # Attach to the custom network

---

This seems to work, but would be a huge help if you tested.

My thought is you create the empty folders for the data and map, but don't let any of the data files into the repo. That way its nice and clean and all data should persist in the same place.

**Comment by Jeppedy** [comment]
So copy no files manually...  Just clone the Git repository and fire it up, yes?

I'll have to test tonight.  All my testing today has been from my cell phone!  That's more than I want to attempt on the small keyboard and screen!  Lol

**Comment by plaintextpackets** [comment]
Yep that's exactly it! Still keeping it with no manual mapping or folder creation, those folders will come down with the repo

Thanks mate

**Comment by PISTOLCUPCAKES** [comment]
I was able to get this running by just cloning the git repo, editing .env for my DNS server, and running `docker compose up`. All looks good!

**Comment by Jeppedy** [comment]
Hmm, I think I must run differently than PISTOLCUPCAKES runs their Docker instance.
I have a permissions issue.  
When I create the directories using 'git clone', my user ID owns them.  But when the directories are made by Docker, they are owned by root.  I had to 'chmod' some of the data and config directories to work around the "Unable to access..." errors.

This is usually worked around by letting the user specify the User to run the container as.  See steps here to make your container more "flexible" to allow users to define the proper user ID: https://dev.to/izackv/running-a-docker-container-with-a-custom-non-root-user-syncing-host-and-container-permissions-26mb

**Comment by plaintextpackets** [comment]
Hmm, ok that makes sense just need to figure out an elegant solution.. I'm thinking either adding an additional install step to chmod the directory (for Linux). Going to try and repro this on my linux server

**Comment by plaintextpackets** [comment]
Are you getting errors like this?

```
 ✔ Container netprobe-probe         Created                                                                              0.0s
 ✔ Container netprobe-presentation  Created                                                                              0.0s
 ✔ Container netprobe-prometheus    Recreated                                                                            3.7s
 ✔ Container netprobe-redis         Created                                                                              0.0s
 ✔ Container netprobe-grafana       Recreated                                                                            3.8s
Attaching to netprobe-grafana, netprobe-presentation, netprobe-probe, netprobe-prometheus, netprobe-redis
netprobe-grafana       | GF_PATHS_DATA='/var/lib/grafana' is not writable.
netprobe-grafana       | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
netprobe-grafana       | mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
netprobe-redis         | 1:C 29 Apr 2024 12:25:20.465 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
netprobe-redis         | 1:C 29 Apr 2024 12:25:20.465 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
netprobe-redis         | 1:C 29 Apr 2024 12:25:20.465 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
```

**Comment by Jeppedy** [comment]
Yep, that's it...

**Comment by plaintextpackets** [comment]
Ok so this is being tracked in issue #6 . Since the latest version pulls the image from dockerhub I'm going to say issue #13 is complete, and we should move the convo to issue #6
